name: node ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x, 22.x, 23.x, 24.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm build
      run: |
        npm ci
        npm run build --if-present
    - name: Running unit tests
      run: npm test
      env:
        CI: true
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v5.5.2
      with:
        # Forks don't have access to secrets, so don't fail their CI builds
        fail_ci_if_error: ${{ github.repository == 'design1online/WTF-Adventure' }}
        directory: ./coverage
        verbose: true